# Generated by Django 4.0.5 on 2022-07-23 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MlbGame',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MlbPlayer',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MlbTeam',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MlbAtBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bat', models.IntegerField()),
                ('inning', models.IntegerField()),
                ('inning_half', models.CharField(max_length=15)),
                ('event_type', models.CharField(max_length=40)),
                ('pitcher_hand', models.CharField(max_length=15)),
                ('batter_hand', models.CharField(max_length=15)),
                ('lineup_position', models.IntegerField()),
                ('single', models.BooleanField()),
                ('double', models.BooleanField()),
                ('triple', models.BooleanField()),
                ('home_run', models.BooleanField()),
                ('scoring_play', models.BooleanField()),
                ('rbi', models.IntegerField()),
                ('earned_runs', models.IntegerField()),
                ('strikeout', models.BooleanField()),
                ('stolen_bases', models.IntegerField()),
                ('error', models.BooleanField()),
                ('description', models.TextField()),
                ('date_updated', models.DateTimeField()),
                ('base_stealer_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stealer_1', to='mlb.mlbplayer')),
                ('base_stealer_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stealer_2', to='mlb.mlbplayer')),
                ('base_stealer_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stealer_3', to='mlb.mlbplayer')),
                ('batter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batter', to='mlb.mlbplayer')),
                ('error_committer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_committer', to='mlb.mlbplayer')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbgame')),
                ('pitcher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher', to='mlb.mlbplayer')),
                ('scoring_player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorer_1', to='mlb.mlbplayer')),
                ('scoring_player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorer_2', to='mlb.mlbplayer')),
                ('scoring_player_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorer_3', to='mlb.mlbplayer')),
                ('scoring_player_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorer_4', to='mlb.mlbplayer')),
            ],
        ),
    ]
