# Generated by Django 4.0.5 on 2022-08-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbplayersimulations',
            name='game_date',
        ),
    ]
