# Generated by Django 4.0.5 on 2022-07-24 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0002_mlblocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbgame',
            name='away_probable_pitcher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_probable_pitcher', to='mlb.mlbplayer'),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='away_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='mlb.mlbteam'),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='game_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='games_in_series_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='games_in_series_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='home_probable_pitcher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_probable_pitcher', to='mlb.mlbplayer'),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='home_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='mlb.mlbteam'),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlb.mlblocation'),
        ),
        migrations.AddField(
            model_name='mlbgame',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
