# Generated by Django 4.0.5 on 2022-07-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0004_remove_mlblocation_name_remove_mlbteam_abbreviation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlbgame',
            old_name='away_probable_pitcher_id',
            new_name='away_probable_pitcher',
        ),
        migrations.RenameField(
            model_name='mlbgame',
            old_name='away_team_id',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='mlbgame',
            old_name='home_probable_pitcher_id',
            new_name='home_probable_pitcher',
        ),
        migrations.RenameField(
            model_name='mlbgame',
            old_name='home_team_id',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='mlbgame',
            old_name='location_id',
            new_name='location',
        ),
    ]
