# Generated by Django 4.0.5 on 2022-08-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0006_mlbplayersimulations_game_date_unix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbplayersimulations',
            name='game_date',
        ),
    ]
