# Generated by Django 4.0.5 on 2022-07-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0006_mlblocation_active_mlblocation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbplayer',
            name='name_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
