# Generated by Django 4.0.5 on 2022-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0007_remove_mlbplayersimulations_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbplayersimulations',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
