# Generated by Django 4.0.5 on 2022-07-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0007_mlbplayer_name_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbatbat',
            name='batter_id',
        ),
        migrations.RemoveField(
            model_name='mlbatbat',
            name='pitcher_id',
        ),
        migrations.AddField(
            model_name='mlbatbat',
            name='batter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batter', to='mlb.mlbplayer'),
        ),
        migrations.AddField(
            model_name='mlbatbat',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_team', to='mlb.mlbteam'),
        ),
        migrations.AddField(
            model_name='mlbatbat',
            name='pitcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitcher', to='mlb.mlbplayer'),
        ),
        migrations.AddField(
            model_name='mlbatbat',
            name='pitching_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitching_team', to='mlb.mlbteam'),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='at_bat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='batter_hand',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='double',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='earned_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='error',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='event_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='game_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbgame'),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='home_run',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='inning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='inning_half',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='lineup_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='pitcher_hand',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='rbi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='scoring_play',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='single',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='stolen_bases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='strikeout',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbatbat',
            name='triple',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
