# Generated by Django 4.0.5 on 2022-08-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0008_mlbplayersimulations_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbplayersimulations',
            name='game_date_unix',
        ),
    ]
