# Generated by Django 4.0.5 on 2022-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0008_remove_mlbatbat_batter_id_remove_mlbatbat_pitcher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbatbat',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='mlblocation',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayer',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayer',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayer',
            name='position_abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayer',
            name='position_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayer',
            name='position_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mlbteam',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbteam',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
