# Generated by Django 4.0.5 on 2022-07-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0009_remove_mlbatbat_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlbUpcomingGames',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_date_time', models.DateTimeField(blank=True, null=True)),
                ('game_type', models.CharField(blank=True, max_length=10, null=True)),
                ('games_in_series_current', models.IntegerField(blank=True, null=True)),
                ('games_in_series_total', models.IntegerField(blank=True, null=True)),
                ('away_probable_pitcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_away_probable_pitcher', to='mlb.mlbplayer')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_away_team', to='mlb.mlbteam')),
                ('home_probable_pitcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_home_probable_pitcher', to='mlb.mlbplayer')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_home_team', to='mlb.mlbteam')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_location', to='mlb.mlblocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='mlbatbat',
            old_name='game_id',
            new_name='game',
        ),
        migrations.CreateModel(
            name='MlbUpcomingPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbupcominggames')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_player', to='mlb.mlbplayer')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_players_team', to='mlb.mlbteam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
