# Generated by Django 4.0.5 on 2022-08-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0009_remove_mlbplayersimulations_game_date_unix'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbbovadaupcomingbatters',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingbatters',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
