# Generated by Django 4.0.5 on 2022-08-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0010_mlbbovadaupcomingbatters_game_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlbBovadaPitchersPostSimData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('stat', models.TextField(blank=True, null=True)),
                ('stat_filter', models.TextField(blank=True, null=True)),
                ('time_interval', models.IntegerField(blank=True, null=True)),
                ('sim_option', models.TextField(blank=True, null=True)),
                ('round_option', models.TextField(blank=True, null=True)),
                ('bet_option', models.TextField(blank=True, null=True)),
                ('bet_line', models.FloatField(blank=True, null=True)),
                ('bet_odds', models.IntegerField(blank=True, null=True)),
                ('expected_prob_avg', models.FloatField(blank=True, null=True)),
                ('actual_result_avg', models.FloatField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
