# Generated by Django 4.0.5 on 2022-08-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0010_mlbupcominggames_rename_game_id_mlbatbat_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlbPlayerPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.TextField(blank=True, null=True)),
                ('time_frame', models.IntegerField(blank=True, null=True)),
                ('filters', models.TextField(blank=True, null=True)),
                ('sim_options', models.CharField(blank=True, max_length=15, null=True)),
                ('result_options', models.CharField(blank=True, max_length=15, null=True)),
                ('bet_options', models.CharField(blank=True, max_length=15, null=True)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('result_type', models.CharField(blank=True, max_length=15, null=True)),
                ('zero', models.FloatField(blank=True, null=True)),
                ('half', models.FloatField(blank=True, null=True)),
                ('one', models.FloatField(blank=True, null=True)),
                ('one_and_half', models.FloatField(blank=True, null=True)),
                ('two', models.FloatField(blank=True, null=True)),
                ('two_and_half', models.FloatField(blank=True, null=True)),
                ('three', models.FloatField(blank=True, null=True)),
                ('three_and_half', models.FloatField(blank=True, null=True)),
                ('four', models.FloatField(blank=True, null=True)),
                ('four_and_half', models.FloatField(blank=True, null=True)),
                ('five', models.FloatField(blank=True, null=True)),
                ('five_and_half', models.FloatField(blank=True, null=True)),
                ('six', models.FloatField(blank=True, null=True)),
                ('six_and_half', models.FloatField(blank=True, null=True)),
                ('seven', models.FloatField(blank=True, null=True)),
                ('seven_and_half', models.FloatField(blank=True, null=True)),
                ('eight', models.FloatField(blank=True, null=True)),
                ('eight_and_half', models.FloatField(blank=True, null=True)),
                ('nine', models.FloatField(blank=True, null=True)),
                ('nine_and_half', models.FloatField(blank=True, null=True)),
                ('ten', models.FloatField(blank=True, null=True)),
                ('ten_and_half', models.FloatField(blank=True, null=True)),
                ('eleven', models.FloatField(blank=True, null=True)),
                ('eleven_and_half', models.FloatField(blank=True, null=True)),
                ('twelve', models.FloatField(blank=True, null=True)),
                ('twelve_and_half', models.FloatField(blank=True, null=True)),
                ('thirteen', models.FloatField(blank=True, null=True)),
                ('thirteen_and_half', models.FloatField(blank=True, null=True)),
                ('fourteen', models.FloatField(blank=True, null=True)),
                ('fourteen_and_half', models.FloatField(blank=True, null=True)),
                ('fifteen', models.FloatField(blank=True, null=True)),
                ('fifteen_and_half', models.FloatField(blank=True, null=True)),
                ('sixteen', models.FloatField(blank=True, null=True)),
                ('sixteen_and_half', models.FloatField(blank=True, null=True)),
                ('seventeen', models.FloatField(blank=True, null=True)),
                ('seventeen_and_half', models.FloatField(blank=True, null=True)),
                ('eighteen', models.FloatField(blank=True, null=True)),
                ('eighteen_and_half', models.FloatField(blank=True, null=True)),
                ('nineteen', models.FloatField(blank=True, null=True)),
                ('nineteen_and_half', models.FloatField(blank=True, null=True)),
                ('twenty', models.FloatField(blank=True, null=True)),
                ('twenty_and_half', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbupcominggames')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulated_player', to='mlb.mlbplayer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
