# Generated by Django 4.0.5 on 2022-08-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0011_mlbbovadapitcherspostsimdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlbBovadaPitchersBetComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('upcoming_game_id', models.IntegerField(blank=True, null=True)),
                ('stat', models.TextField(blank=True, null=True)),
                ('bet_option', models.TextField(blank=True, null=True)),
                ('bovada_bet_line', models.FloatField(blank=True, null=True)),
                ('bovada_bet_odds', models.IntegerField(blank=True, null=True)),
                ('bovada_implied_probability', models.FloatField(blank=True, null=True)),
                ('sim_bet_odds', models.IntegerField(blank=True, null=True)),
                ('sim_implied_probability', models.FloatField(blank=True, null=True)),
                ('expected_value_per_unit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
