# Generated by Django 4.0.5 on 2022-08-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0011_mlbplayerpredictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbplayerpredictions',
            name='game_date',
        ),
        migrations.AddField(
            model_name='mlbplayerpredictions',
            name='actual_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayerpredictions',
            name='game_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
