# Generated by Django 4.0.5 on 2022-08-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0012_remove_mlbplayerpredictions_game_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbplayerpredictions',
            name='game_date_time',
        ),
        migrations.AddField(
            model_name='mlbplayerpredictions',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbplayerpredictions',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbgame'),
        ),
    ]
