# Generated by Django 4.0.5 on 2022-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0012_mlbbovadapitchersbetcomparison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlbplayersimulations',
            old_name='player',
            new_name='player_id',
        ),
        migrations.AddField(
            model_name='mlbplayersimulations',
            name='player_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
