# Generated by Django 4.0.5 on 2022-08-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0013_remove_mlbplayerpredictions_game_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlbPlayerSimulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField(blank=True, null=True)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('statistic', models.TextField(blank=True, null=True)),
                ('time_frame', models.IntegerField(blank=True, null=True)),
                ('stat_filters', models.TextField(blank=True, null=True)),
                ('prev_values', models.BinaryField(blank=True, null=True)),
                ('prev_avg', models.FloatField(blank=True, null=True)),
                ('prev_st_dev', models.FloatField(blank=True, null=True)),
                ('sim_values', models.BinaryField()),
                ('sim_avg', models.FloatField()),
                ('sim_st_dev', models.FloatField()),
                ('actual_value', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulated_player', to='mlb.mlbplayer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MlbPlayerPredictions',
        ),
    ]
