# Generated by Django 4.0.5 on 2022-08-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0014_mlbplayersimulations_delete_mlbplayerpredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlbBovadaUpcomingBatters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('player_bov_id', models.IntegerField(blank=True, null=True)),
                ('home_run_odds', models.IntegerField(blank=True, null=True)),
                ('home_run_twice_odds', models.IntegerField(blank=True, null=True)),
                ('steal_base_odds', models.IntegerField(blank=True, null=True)),
                ('record_hit_odds', models.IntegerField(blank=True, null=True)),
                ('record_rbi_odds', models.IntegerField(blank=True, null=True)),
                ('two_bases_odds', models.IntegerField(blank=True, null=True)),
                ('three_bases_odds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MlbBovadaUpcomingPitchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.TextField(blank=True, null=True)),
                ('player_bov_id', models.IntegerField(blank=True, null=True)),
                ('strikeout_line', models.IntegerField(blank=True, null=True)),
                ('strikeout_over_odds', models.IntegerField(blank=True, null=True)),
                ('strikeout_under_odds', models.IntegerField(blank=True, null=True)),
                ('pitching_out_line', models.IntegerField(blank=True, null=True)),
                ('pitching_out_over_odds', models.IntegerField(blank=True, null=True)),
                ('pitching_out_under_odds', models.IntegerField(blank=True, null=True)),
                ('earned_runs_line', models.IntegerField(blank=True, null=True)),
                ('earned_runs_over_odds', models.IntegerField(blank=True, null=True)),
                ('earned_runs_under_odds', models.IntegerField(blank=True, null=True)),
                ('hits_allowed_line', models.IntegerField(blank=True, null=True)),
                ('hits_allowed_over_odds', models.IntegerField(blank=True, null=True)),
                ('hits_allowed_under_odds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mlbupcomingplayers',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbupcomingplayers',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
