# Generated by Django 4.0.5 on 2022-08-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0015_remove_mlbplayersimulations_game_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_code', models.CharField(blank=True, max_length=100, null=True)),
                ('file_code', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('franchise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('club_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('league_name', models.CharField(blank=True, max_length=100, null=True)),
                ('division_name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_venue', to='mlb.venue')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_title', models.CharField(blank=True, max_length=100, null=True)),
                ('position_code', models.IntegerField(blank=True, null=True)),
                ('position_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position_type', models.CharField(blank=True, max_length=100, null=True)),
                ('position_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('bat_side_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bat_side_description', models.CharField(blank=True, max_length=100, null=True)),
                ('pitch_hand_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pitch_hand_description', models.CharField(blank=True, max_length=100, null=True)),
                ('strike_zone_top', models.FloatField(blank=True, null=True)),
                ('strike_zone_bottom', models.FloatField(blank=True, null=True)),
                ('is_player', models.BooleanField(blank=True, null=True)),
                ('current_age', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_current_team', to='mlb.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('abstract_game_state', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract_game_code', models.CharField(blank=True, max_length=10, null=True)),
                ('coded_game_state', models.CharField(blank=True, max_length=10, null=True)),
                ('detailed_state', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('away_is_winner', models.BooleanField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('home_is_winner', models.BooleanField(blank=True, null=True)),
                ('double_header', models.CharField(blank=True, max_length=10, null=True)),
                ('day_night', models.CharField(blank=True, max_length=100, null=True)),
                ('total_games_in_series', models.IntegerField(blank=True, null=True)),
                ('current_game_in_series', models.IntegerField(blank=True, null=True)),
                ('series_description', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='mlb.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='mlb.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_venue', to='mlb.venue')),
            ],
        ),
    ]
