# Generated by Django 4.0.5 on 2022-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0016_rename_earned_runs_line_mlbbovadaupcomingpitchers_walks_over_odds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='earned_runs_over_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='earned_runs_over_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='earned_runs_under_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='earned_runs_under_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='hits_allowed_over_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='hits_allowed_over_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='hits_allowed_under_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='hits_allowed_under_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='pitching_out_over_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='pitching_out_over_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='pitching_out_under_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='pitching_out_under_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='strikeout_over_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='strikeout_over_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='strikeout_under_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='strikeout_under_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='walks_over_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='walks_over_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='walks_under_line',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingpitchers',
            name='walks_under_odds',
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='over_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='over_odds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='stat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='under_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingpitchers',
            name='under_odds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
