# Generated by Django 4.0.5 on 2022-08-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0017_remove_mlbbovadaupcomingpitchers_earned_runs_over_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='home_run_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='home_run_twice_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='player_bov_id',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='record_hit_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='record_rbi_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='steal_base_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='three_bases_odds',
        ),
        migrations.RemoveField(
            model_name='mlbbovadaupcomingbatters',
            name='two_bases_odds',
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingbatters',
            name='odds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingbatters',
            name='over_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbbovadaupcomingbatters',
            name='stat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlbplayer',
            name='current_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_current_team', to='mlb.mlbteam'),
        ),
    ]
